name: Deploy to production
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build files
    runs-on: ubuntu-latest
    steps: 
      - name: Setup node
        uses: actions/setup-node@v1
        with: 
            node-version: '10.x'
      - uses: actions/checkout@master
      - name: Build project files
        run: |
          npm install
          npm run build

  deploy: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to s3
        env: 
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: 
          aws s3 cp ./dist/ s3://philagov-vue-apps/programs --recursive # change it
